# Generated by Django 5.0.1 on 2026-05-23 12:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('sfh', 'Single Family Home'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('quad', 'Quadplex'), ('multiunit', 'Multi-Unit'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base Case', max_length=200)),
                ('purchase_year', models.IntegerField(default=2026)),
                ('analysis_horizon_years', models.IntegerField(default=30)),
                ('sale_year', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('down_payment_pct', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('annual_appreciation_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=5)),
                ('transfer_tax_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5)),
                ('lender_fees', models.DecimalField(decimal_places=2, default=Decimal('4000.00'), max_digits=10)),
                ('title_insurance', models.DecimalField(decimal_places=2, default=Decimal('3500.00'), max_digits=10)),
                ('inspection_appraisal', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10)),
                ('attorney_fees', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('other_closing_costs', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0650'), max_digits=5)),
                ('term_years', models.IntegerField(default=30)),
                ('pmi_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0050'), max_digits=5)),
                ('annual_rent_growth_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=5)),
                ('vacancy_rate_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('property_mgmt_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5)),
                ('property_tax_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0120'), max_digits=5)),
                ('insurance_annual', models.DecimalField(decimal_places=2, default=Decimal('2400.00'), max_digits=10)),
                ('hoa_annual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('maintenance_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5)),
                ('utilities_annual', models.DecimalField(decimal_places=2, default=Decimal('2400.00'), max_digits=10)),
                ('expense_inflation_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), max_digits=5)),
                ('selling_costs_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0600'), max_digits=5)),
                ('scenario_appreciation_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5)),
                ('scenario_rent_growth_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=5)),
                ('scenario_vacancy_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('scenario_expense_inflation_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0150'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='api.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Unit 1', max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_occupied_years', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.projection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
