# Generated by Django 5.0.1 on 2026-05-24 00:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='estimated_annual_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='projection',
            name='repairs_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
