# Generated by Django 5.0.1 on 2026-05-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projection_estimated_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='refinance_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='refinance_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
