# Generated by Django 5.0.1 on 2026-05-24 03:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projection_refinance_rate_projection_refinance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='monthly_prepayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
